github: marsdeat
ko_fi: marsdeat
buy_me_a_coffee: marsdeat
custom: ["https://monzo.me/andrewmarsden2/2.00?h=Db49Cx&d=Tip%20jar","https://www.paypal.com/paypalme/atmarsden95?country.x=GB&locale.x=en_GB"]